### PR TITLE
Modify to make it work with mautrix-go v0.8.0

### PR DESCRIPTION
**Pull request by tripleFA**
- Modifications to make this work with mautrix-go v0.8.0. 
- Changed the way the bot connect to a Matrix homeserver.
- Added support for encoding other than UTF-8. I only tested ISO-8859-1

Should correct #36

### CODE REVIEW

**Comment by JojiiOfficial** [comment]
Thanks for your PR!
Although I have to say it doesn't work for me. The bridge joins the room but it doesn't act upon my messages. `!login` doesn't do anything and after debugging I found out, my user's messages don't trigger the message-event listener at all.

**Comment by tripleFA** [comment]
Hi,
That strange. It's working on my setup.
Are you running the current matrix synapse server?
I'm new to Go so I might miss something obvious.
Capture d’écran du 2021-02-21 12-42-33

**Comment by JojiiOfficial** [comment]
This is weird. I don't run a synapse server anymore, I tested it using matrix.org's instance. Therefore I created a test user. The bridge connects and the joining works too. Also the first `!login`-info-message gets sent twice each time with this setup. I haven't used matrix for a long time so even I could've missed something.

**Comment by tripleFA** [comment]
I created a bot account on matrix.org instance and it does not work... o_O
I gonna have to investigate a bit.
The first message is send twice but I haven't look into that

**Comment by tripleFA** [comment]
Okay, I think I got it :
- Create a bot user
- **Disconnect** from the client
- Leave the room you were sharing with the bot
- Create a new one and invite the bot
- Should be able to login
I don't know if it is an issue from our side, mautrix-go side or if the logged client catches the new message before the bot

**Comment by JojiiOfficial** [comment]
Good job, this works for me too!
The bot could check for already existing sessions and remove those but this is another issue.

**Pull request merged**
